# GoReleaser configuration file for Terraform Plugin
version: 1
# before:
#   hooks:
#     - go mod tidy

# builds:
#   - env:
#       - CGO_ENABLED=0  # Disables CGO for portability
#     mod_timestamp: '{{ .CommitTimestamp }}'
#     flags:
#       - -trimpath
#     ldflags:
#       - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
#     goos:
#       - freebsd
#       - windows
#       - linux
#       - darwin
#     goarch:
#       - amd64
#       - '386'
#       - arm
#       - arm64
#     ignore:
#       - goos: darwin
#         goarch: '386'
#     binary: '{{ .ProjectName }}'

archives:
  - format: zip  # Preferred format for Terraform plugins
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

# checksum:
#   name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
#   algorithm: sha256
#   extra_files:
#     - glob: 'terraform-registry-manifest.json'
#       name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  # Set this to true during testing to avoid accidental public releases
  draft: false

changelog:
  disable: false
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
